### ISSUE TITLE
App Bridge v4 prevents the app from being installed

### ISSUE THREAD

**Issue by szanuje** [ozzyonfire/shopify-next-app#14]
Hello, I updated the app bridge to version 4 and added new html tags.

```
      <head>
        <meta name="test" content="test" />
        <script src="https://cdn.shopify.com/shopifycloud/app-bridge.js" />
      </head>
```

Unfortunately, it prevents me from installing the app on my dev store. I get the 404 page.

Once I remove the <script> tag, it lets me install the app, but then I can't make authenticated requests in the app without the script.

Did you have the same problem when migrating?

**Comment by ozzyonfire** [comment]
I haven't had this issue. Make sure you are using the proper config settings in your .toml. 

Specifically you need to make sure you have:
```toml
[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
use_legacy_install_flow = false
```
